### ISSUE TITLE
Fix deployment build

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/senecajs.org#140]
Currently failing: 

https://travis-ci.org/senecajs/senecajs.org/builds/100392805#L217

**Comment by AdrieanKhisbe** [comment]
Here is the error: 

```js
> metalsmith
  Metalsmith · The partial head could not be found
Error: The partial head could not be found
    at Object.invokePartial (/home/travis/build/senecajs/senecajs.org/node_modules/handlebars/dist/cjs/handlebars/runtime.js:266:11)
    at Object.invokePartialWrapper [as invokePartial] (/home/travis/build/senecajs/senecajs.org/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at Object.eval (eval at createFunctionContext (/home/travis/build/senecajs/senecajs.org/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:28)
    at main (/home/travis/build/senecajs/senecajs.org/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/travis/build/senecajs/senecajs.org/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/travis/build/senecajs/senecajs.org/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at /home/travis/build/senecajs/senecajs.org/node_modules/metalsmith-layouts/node_modules/consolidate/lib/consolidate.js:713:16
    at /home/travis/build/senecajs/senecajs.org/node_modules/metalsmith-layouts/node_modules/consolidate/lib/consolidate.js:146:5
    at tryCatcher (/home/travis/build/senecajs/senecajs.org/node_modules/metalsmith-layouts/node_modules/consolidate/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/travis/build/senecajs/senecajs.org/node_modules/metalsmith-layouts/node_modules/consolidate/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/home/travis/build/senecajs/senecajs.org/node_modules/metalsmith-layouts/node_modules/consolidate/node_modules/bluebird/js/main/promise.js:70:37)
    at promisify (/home/travis/build/senecajs/senecajs.org/node_modules/metalsmith-layouts/node_modules/consolidate/lib/consolidate.js:139:10)
    at Function.exports.handlebars.render (/home/travis/build/senecajs/senecajs.org/node_modules/metalsmith-layouts/node_modules/consolidate/lib/consolidate.js:703:10)
    at /home/travis/build/senecajs/senecajs.org/node_modules/metalsmith-layouts/node_modules/consolidate/lib/consolidate.js:167:27
    at /home/travis/build/senecajs/senecajs.org/node_modules/metalsmith-layouts/node_modules/consolidate/lib/consolidate.js:101:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

```

**Comment by AdrieanKhisbe** [comment]
Note: from 3ac985bbd4a4bfbc95e8fb9583303db5a2119633, the travis will be failing if error when building the static site

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean @orlacoding @geek.
Any hint, intuition, or hunch :grey_question:

**Comment by AdrieanKhisbe** [comment]
Answer might be there: https://github.com/superwolff/metalsmith-layouts
But I have no time to investigate right now.

**Comment by AdrieanKhisbe** [comment]
:clap: @geek :exclamation: :D
