### ISSUE TITLE
Seneca Getting Started Example issue - app.use() requires middleware functions

### ISSUE THREAD

**Issue by LogOg** [senecajs/senecajs.org#282]
When running app.js from: http://senecajs.org/getting-started/
i.e. :
var seneca = require('seneca')()
	.use('api')
	.client({type:'tcp',pin:'role:math'})
var app = require('express')()
	.use(require('body-parser').json())
	.use(seneca.export('web'))
	.listen(3000)

As follows: node app.js --seneca.log=plugin:web,plugin:api
Get the following for line .use(seneca.export('web')):

{"kind":"notice","notice":"hello seneca p0r05xeeb8ir/1479215163013/6993/3.2.2/-","level":"info","when":1479215163052}
[]
/Users/macbookpro/worknode/node_modules/express/lib/application.js:209
    throw new TypeError('app.use() requires middleware functions');
    ^
TypeError: app.use() requires middleware functions
    at Function.use (/Users/macbookpro/worknode/node_modules/express/lib/application.js:209:11)
    at Object.<anonymous> (/Users/macbookpro/worknode/microservice/app.js:9:3)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)

**Comment by Shobhit28** [comment]
I am facing the same issue . Any fix @LogOg ?
