### ISSUE TITLE
Error running "Live Logs in your Browser" sample.

### ISSUE THREAD

**Issue by mingfang** [senecajs/senecajs.org#99]
The "Live Logs in Your Browser" sample here http://senecajs.org/tutorials/logging-with-seneca.html has a line like this 
```var server = http.createServer(seneca.service())```
I'm getting this error when trying to run it.
```
var server = http.createServer(seneca.service())
                                      ^
TypeError: undefined is not a function
    at Object.<anonymous> (/root/seneca/test.js:8:39)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by vtardia** [comment]
Fixed in https://github.com/senecajs/senecajs.org/commit/545c4ebcaf928324a1fe68baa25bd9ef49565d09, fixed examples are in senecajs/seneca#242
